### PR TITLE
Actions: Use Matrix and Xcode 11.4

### PR DESCRIPTION
**Pull request by freak4pc**

### CODE REVIEW

**Comment by freak4pc** [comment]
@jasdev I remembered you wanted to use 11.4 for something, this PR takes care of it

**Comment by jasdev** [comment]
Woot! Mind if I sneak one more PR with that 11.4-related update before the 1.1.0 release?

**Comment by freak4pc** [comment]
If it’s today or tomorrow, absolutely :)

**Comment by jasdev** [comment]
Just kidding, forgot the Swift 5.2 feature I wanted to lean on is no longer needed with `.removeAllDuplicates`’s `filter`-based implementation—all clear. 😄

**Pull request merged**
